name: culhwch

services:
  culhwch-front:
    container_name: culhwch-front
    restart: always
    profiles:
      - culhwch
      - all
    depends_on:
      culhwch-api:
        condition: service_healthy
    image: ${CULHWCH_FRONT_IMAGE:-ghcr.io/kamchatskiy/culhwch-front:latest}
    networks:
      - culhwch
    ports:
      - 20003:80
    expose:
      - 80

  culhwch-api:
    container_name: culhwch-api
    restart: always
    profiles:
      - culhwch
      - all
    depends_on:
      culhwch-db:
        condition: service_healthy
    image: ${CULHWCH_API_IMAGE:-ghcr.io/kamchatskiy/culhwch-api:latest}
    command: python app.py
    environment:
      DB_HOST: culhwch-db
      POSTGRES_DB: culhwch
      POSTGRES_USER: culhwch
      POSTGRES_PASSWORD: ${PASSWORD}
      SERVER_PASSWORD: ${PASSWORD}
    networks:
      - culhwch
    expose:
      - 3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  culhwch-db:
    container_name: culhwch-db
    restart: always
    profiles:
      - culhwch
      - all
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: culhwch
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: culhwch
    networks:
      - culhwch
    expose:
      - 5432
    volumes:
      - ${DATA_DIR}/culhwch/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U culhwch -d culhwch
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  culhwch:
