name: portainer

services:
  portainer-app:
    container_name: portainer
    privileged: true
    restart: always
    profiles:
      - portainer_app
      - all
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    environment:
      - PASSWORD=${PASSWORD}
    networks:
      - portainer
    ports:
      - 20000:9443
    volumes:
      - ${DATA_DIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-agent:
    container_name: portainer_agent
    restart: always
    profiles:
      - portainer_agent
      - all
    image: ${PORTAINER_AGENT_IMAGE:-portainer/agent:latest}
    environment:
      - AGENT_SECRET={PASSWORD}
    networks:
      - portainer
    ports:
      - 20001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  portainer:
