name: portainer

services:
  app:
    container_name: portainer
    profiles:
      - portainer_app
      - all
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    privileged: true
    restart: always
    ports:
      - 9443:9443
    volumes:
      - ${DATA_DIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    command: --admin-password ${PASSWORD}

  agent:
    container_name: portainer_agent
    profiles:
      - portainer_agent
      - all
    image: ${PORTAINER_AGENT_IMAGE:-portainer/agent:latest}
    restart: always
    environment:
      - AGENT_SECRET={PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
